# Generated by Django 2.2.1 on 2019-06-01 17:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillUpBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Fill Up Broker', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='USD', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transfer_value_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='USD', editable=False, max_length=3)),
                ('transfer_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14)),
                ('transaction_type', models.CharField(default='Transfer', max_length=20)),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_by_source', to='wallets.Wallet')),
                ('target_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillUpTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transfer_value_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='USD', editable=False, max_length=3)),
                ('transfer_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14)),
                ('transaction_type', models.CharField(default='FillUp', max_length=20)),
                ('source_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.FillUpBroker')),
                ('target_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
